name: Python CI/CD avansat

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install flake8 pytest

      - name: Lint with flake8
        run: flake8 .

      - name: Run script (if script.py exists)
        run: |
          if [ -f script.py ]; then
            python script.py
          fi
        shell: bash

      - name: Run tests and save results
        run: |
          pytest > result.log
          cat result.log

      - name: Upload pytest result log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pytest-result-log
          path: result.log
